language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: VTK_VERSION=6.2
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: VTK_VERSION=7.0
    - os: osx
      compiler: clang
      osx_image: xcode7.3
      sudo: required
      env: VTK_VERSION=6.2
    - os: osx
      compiler: clang
      osx_image: xcode7.3
      sudo: required
      env: VTK_VERSION=7.0
  allow_failures:
    - os: osx
    - env: VTK_VERSION=7.0

addons:
  apt:
    packages:
    - curl
    - cmake

git:
  submodules: false

before_install:
  - export NUM_THREADS=4
  - export cwd=$(pwd)
  - export SCRIPTS=$cwd/Travis
  - export EXTERNALS_DIR=~/travis/external
  - export VTK_SOURCE_DIR=$EXTERNALS_DIR/vtk-$VTK_VERSION
  - export VTK_DIR=$EXTERNALS_DIR/vtk-$VTK_VERSION-build
  - export BUILD_DIR=$cwd/build

cache:
  directories:
  - ~/travis/external/vtk-6.2
  - ~/travis/external/vtk-6.2-build
  - ~/travis/external/vtk-7.0
  - ~/travis/external/vtk-7.0-build
  timeout: 900


before_script:
  - $SCRIPTS/travis_build_vtk.sh

script: $SCRIPTS/travis_build_and_test.sh
